import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider";
import ClientAuthProvider from "../components/AuthProvider";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/components/SessionWrapper";
// import { Provider } from "next-auth/react"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <body className={inter.className}>{children}</body></ThemeProvider>
      </html>
    </SessionWrapper>
  );
}
